---
- name: Prepare MacOS Device
  hosts: all
  become: true

  vars_files:
    - vars_base.yml
  pre_tasks:
    - name: Install Homebrew
      include_tasks: '{{ ansible_path }}/_install_homebrew.yml'

