---
- name: Check and install Homebrew
  block:
    - name: Check Homebrew existence
      stat:
        path: /usr/local/bin/brew
      register: homebrew_exist

    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when: not homebrew_exist.stat.exists

    - name: Disable Homebrew analytics
      lineinfile:
        path: '{{ home_path }}/{{ item }}'
        line: export HOMEBREW_NO_ANALYTICS=1
        create: true
      loop:
        - '.bash_profile'
        - '.zprofile'

  when: ansible_distribution=="Darwin"
  tags: brew
