---
- name: Config MacOS
  block:
    # Hosts
    - name: Set hosts
      block:
        - name: Read hosts from file
          set_fact:
            hosts_content: "{{ lookup('file', '{{ system_conf_path }}/hosts') }}"

        - name: Append hosts
          lineinfile:
            path: /etc/hosts
            line: '{{ item }}'
          loop: "{{ hosts_content.split('\n') }}"
          when: item | trim != ''
      tags: hosts

    # Local config
    - name: Apply local config
      command: bash {{ script_path }}/config_local.sh
      become_user: '{{ user }}'
      tags: local_config

  when: ansible_os_family=="Darwin"
