---
- name: Config MacOS
  hosts: all
  become: true

  vars_files:
    - _vars_base.yml

  pre_tasks:
    - name: Create local dirs
      include_tasks: '{{ ansible_path }}/_create_local_dirs.yml'

  tasks:
    # Hosts
    - name: Set hosts
      block:
        - name: Read hosts from file
          set_fact:
            hosts_content: "{{ lookup('file', '{{ system_conf_path }}/hosts') }}"

        - name: Append hosts
          lineinfile:
            path: /etc/hosts
            line: '{{ item }}'
          loop: "{{ hosts_content.split('\n') }}"
          when: item | trim != ''

      when: ansible_os_family=="Darwin"
      tags: hosts

    # Local config
    - name: Apply local config
      command: bash {{ script_path }}/config_local.sh

      become_user: '{{ user }}'
      when: ansible_os_family=="Darwin"
      tags: local_config
