---
# Hosts
- name: Set hosts
  block:
    - name: Read hosts from file
      set_fact:
        hosts_content: "{{ lookup('file', '{{ system_conf_path }}/hosts') }}"

    - name: Append hosts
      lineinfile:
        path: /etc/hosts
        line: '{{ item }}'
      loop: "{{ hosts_content.split('\n') }}"
      when: item | trim != ''

  when: ansible_os_family=="Darwin"
  tags: hosts

# Packages
- name: Install base pkgs
  block:
    - name: Install homebrew pkgs
      block:
        - name: Add taps to MacOS
          homebrew_tap:
            name: '{{ tap_list }}'
            state: present

        - name: Install base brew pkgs to MacOS
          homebrew:
            name: '{{ core_brew_list }}'
            state: present
            update_homebrew: true

        - name: Install base cask pkgs to MacOS
          homebrew_cask:
            name: '{{ core_cask_list }}'
            state: present

    - name: Install and config Oh My ZSH
      block:
        - name: Run omz install script
          shell:
            cmd: >
              curl -o- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
            creates: '{{ local_opt_path }}/oh-my-zsh/oh-my-zsh.sh'
          environment:
            ZSH: '{{ local_opt_path }}/oh-my-zsh'
            CHSH: 'no'
            RUNZSH: 'no'

        - name: Install OMZ plugins
          git:
            repo: https://github.com/zsh-users/{{ item }}.git
            dest: '{{ local_opt_path }}/oh-my-zsh/custom/plugins/{{ item }}'
            version: master
            update: true
          with_items: [zsh-syntax-highlighting, zsh-autosuggestions]

        - name: Config OMZ
          block:
            - name: Create omz config directory
              file:
                path: '{{ local_config_path }}/omz'
                state: directory
                owner: '{{ user }}'
                mode: 0700
            - name: Make .zshrc symlink
              file:
                src: '{{ omz_path }}/.zshrc'
                dest: '{{ home_path }}/.zshrc'
                state: link
                force: true
                owner: '{{ user }}'
                mode: 0700
            - name: Make config symlinks
              file:
                src: '{{ omz_path }}/{{ item }}'
                dest: '{{ local_config_path }}/omz/{{ item }}'
                state: link
                force: true
                owner: '{{ user }}'
                mode: 0700
              with_items: alias_zsh

    - name: Download some scripts
      get_url:
        url: https://raw.githubusercontent.com/ggragham/just_bunch_of_scripts/master/bin/{{ item }}
        dest: '{{ local_bin_path }}/'
        mode: 0700
      with_items: '{{ script_list }}'

  become_user: '{{ user }}'
  when: ansible_os_family=="Darwin"
  tags: pkgs

# Local config
- name: Apply local config
  command: 'bash {{ script_path }}/config_local.sh'
  become_user: '{{ user }}'
  tags: local_config
